// <auto-generated />
using System;
using ApiRemedio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRemedio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ApiRemedio.RemedioEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("dataValidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("miligramas")
                        .HasColumnType("REAL");

                    b.Property<string>("nomeRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Remedios");
                });
#pragma warning restore 612, 618
        }
    }
}
